# Site settings
baseurl = "https://datatonanticorrupcion.mx/"
languageCode = "es-mx"
defaultContentLanguage = "es"
title = "Datatón Anticorrupción"
theme = "dataton-agency"
publishDir = "docs"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-21077034-33"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/

  # Metadata for search engines
  name = "Dataton anticorrupcion"
  description = """El datatón anticorrupción es un evento donde construiremos herramientas 
  que utilicen datos abiertos con el fin de combatir la corrupción en México."""
  image = "https://datatonanticorrupcion.mx/img/dataton-card.png"
  twitter_user = "@SESNAOficial"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "No se encontró esa página"
    text = "Por favor visita [esta página](/)"

  # Navigation
  [params.navigation]
    brand = "Datatón Anticorrupción 2019"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    info = "Convocatoria"
    registro = "Registro"
    team = "Mentores"
    sede = "Sede"
 
    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. 

    # postpended links
    [[menu.postpend]]
      url = "/info/temas"
      name = "Temas"
      weight = 6

    [[menu.postpend]]
      url = "/info/datos"
      name = "Datos"
      weight = 7

    [[menu.postpend]]
      url = "/info/reglas"
      name = "Reglas"
      weight = 8

    [[menu.postpend]]
      url = "/info/preguntas-frecuentes"
      name = "Dudas"
      weight = 9

  # Sección de hero en homepage. 
  [params.hero]
  # Dado que el layout es muy particular para este evento, el contenido está 
  # hardcoded en layouts/partials/hero.html

  # Sección de información clave
  [params.info]
    enable = true
    title = "Convocatoria"
    description= """Te invitamos a participar en el datatón anticorrupción, un evento donde construiremos 
herramientas que utilicen datos abiertos con el fin de combatir la corrupción en nuestro país.

#### Fecha y sede
El evento se realizará el **sábado 7 de diciembre de 9 a 20 hrs** en la Escuela de Gobierno y Transformación Pública del Tecnológico de Monterrey, sede Mixcoac ubicada en 

> Av. Revolución 756, CDMX.

#### Dirigido a
Aunque la participación es abierta, consideramos que las personas que más pueden aportar son aquellas con experiencia 
en alguno de los siguientes campos: ciencia de datos, desarrollo de software, comunicación, y diseño. Dado que tenemos 
una capacidad limitada en la sede, daremos prioridad de participación a las personas con estos roles.

#### Quién convoca
Este evento es una iniciativa de la [Plataforma Digital Nacional](https://plataformadigitalnacional.org) con el patrocinio de USAID, y es producido por <a href="https://sg.com.mx">Software Guru</a>.
"""

  # Sección para registro
  [params.registro]
    enable = false
    title = "Registro"
    description = """<p>El registro se ha cerrado.</p>
    <p>Pronto publicaremos
    aquí información sobre los proyectos desarrollados.</p>
    """

  # Sección para sede
  [params.sede]
  enable = false
  title = "Sede"
  name = "Escuela de Gobierno y Transformación Pública del Tecnológico de Monterrey"
  description = """Av. Revolución #756, Col. Mixcoac. CDMX
  https://escueladegobierno.itesm.mx/acerca-de-la-escuela
  """

  # Team section
  [params.team]
    enable = true
    #center = true
    title = "Mentores"

    # Las fotos de los mentores se almacenan en 'static/img/team'.
    # Tratar de utilizar imágenes de por lo menos 360px*360px.

    [[params.team.members]]
      img = "paola_villarreal.jpg"
      name = "Paola Villarreal"
      position = "Director of Product Engineering @ Creative Commons"
      social = [
        ["fa-twitter", "https://twitter.com/paw"],
        ["fa-linkedin", "https://www.linkedin.com/in/pawmx/"]
      ]

    [[params.team.members]]
      img = "sofia_ramirez.jpg"
      name = "Sofía Ramírez"
      position = "Directora Adjunta de Investigación Aplicada @ Mexicanos contra la Corrupción y la Impunidad"
      social = [
        ["fa-twitter", "https://twitter.com/sofia_ramireza"],
      ]

    [[params.team.members]]
      img = "alexandra_zapata.jpg"
      name = "Alexandra Zapata"
      position = "Directora de Educación e Innovación Cívica @ Instituto Mexicano para la Competitividad (IMCO)"
      social = [
        ["fa-twitter", "https://twitter.com/azapatah"],
        ["fa-linkedin", "https://www.linkedin.com/in/azapatah/"]
      ]
      
    [[params.team.members]]
      img = "diana_sifuentes.jpg"
      name = "Diana Sifuentes"
      position = "Data Scientist @ Data2B"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/dianasifuentesmunch/"]
      ]

    [[params.team.members]]
      img = "jose_toral.jpg"
      name = "José Manuel Toral"
      position = "Especialista de datos @ Mexicanos contra la Corrupción y la Impunidad"
      social = [
        ["fa-twitter", "https://twitter.com/jmtoralc"],
        ["fa-linkedin", "https://www.linkedin.com/in/josetoral/"]
      ]

    [[params.team.members]]
      img = "jm_casanueva.jpg"
      name = "Juan Manuel Casanueva"
      position = "Director Ejecutivo @ Social TIC"
      social = [
        ["fa-twitter", "https://twitter.com/jm_casanueva"],
        ["fa-linkedin", "https://www.linkedin.com/in/jmcasanueva/"]
      ]

    [[params.team.members]]
      img = "jorge_a_castaneda.jpg"
      name = "Jorge Andrés Castañeda"
      position = "Coordinador de Proyectos @ Instituto Mexicano para la Competitividad (IMCO)"
      social = [
        ["fa-twitter", "https://twitter.com/jorgeacast"],
        ["fa-linkedin", "https://www.linkedin.com/in/jorge-andres-castaneda-0044a75/"]
      ]

    [[params.team.members]]
      img = "jesus_ramos.jpg"
      name = "Jesús Ramos"
      position = "Director de Operaciones @ Datank.ai"
      social = [
        ["fa-twitter", "https://twitter.com/xuxoramos"],
        ["fa-linkedin", "https://www.linkedin.com/in/xuxoramos/"]
      ]



  # Sponsors section
  # Los logos de los aliados están en 'static/img/logos'.
  # El tamaño ideal es 280px*80px
    [params.sponsors]
      enable = true
      center = true

    [params.sponsors1_list]
      enable = true
      title = "Organizado por"

      [[params.sponsors1]]
        logo = "pdn_logo_texto.png"
        link = "https://plataformadigitalnacional.org"

      [[params.sponsors1]]
        logo = "sesna.png"
        link = "https://www.gob.mx/sesna"

    [params.sponsors2_list]
      enable = true
      title = "Con el apoyo de" 

      [[params.sponsors2]]
        logo = "usaid.png"
        link = "https://www.usaid.gov"

      [[params.sponsors2]]
        logo = "coparmex.png"
        link = "https://coparmex.org.mx"

      [[params.sponsors2]]
        logo = "DSAM.png"
        link = "https://www.datascienceacademy.com.mx"

      [[params.sponsors2]]
        logo = "unodc.png"
        link = "https://www.unodc.org/unodc/es/index.html"

      [[params.sponsors2]]
        logo = "uk.png"
        link = "https://www.gov.uk/world/organisations/british-embassy-mexico-city.es-419"

      [[params.sponsors2]]
        logo = "pnud.png"
        link = "http://www.undp.org/content/undp/es/home.html"

      [[params.sponsors2]]
        logo = "integrity.png"
        link = "https://www.allianceforintegrity.org/es/"

      [[params.sponsors2]]
        logo = "cpc.png"
        link = "https://cpc.org.mx/"

      [[params.sponsors2]]
        logo = "nostarch.png"
        link = "https://nostarch.com/"

    [params.sponsors3_list]
      enable = true
      title = "Producido por"

      [[params.sponsors3]]
        logo = "sg.png"
        link = "https://sg.com.mx"

  #FAQ
  [params.faq_list]
    enable = true

    [[params.faq]]
      question = "¿Quiénes pueden participar?"
      answer = """La participación es abierta, pero tenemos cupo limitado. 
Consideramos que las personas que más pueden aportar son aquellas con experiencia en alguno de los 
siguientes campos: ciencia de datos, desarrollo de software, comunicación, y diseño. 

Si te interesa participar, por favor llena la forma de solicitud de participación. 
"""

    [[params.faq]]
      question = "¿Requiero llevar mi propio equipo de cómputo?"
      answer = "Sí, por favor lleva tu propio equipo."

    [[params.faq]]
      question = "Somos varias personas que queremos participar, ¿todos deben llenar la solicitud?"
      answer = "Sí, cada uno debe llenar la solicitud de participación."

    [[params.faq]]
      question = "¿Qué datos usaremos?"
      answer = "Puedes consultar los datos disponibles en la sección datos https://datatonanticorrupcion.mx/info/datos/"

    [[params.faq]]
      question = "¿Hay tamaño máximo de miembros por equipo?"
      answer = "5 personas es el máximo por equipo"

    [[params.faq]]
      question = "¿Hay premios?"
      answer = "Sí, El premio principal será un paquete con regalos y herramientas de utilidad para todos los perfiles en el equipo, No será dinero. Te aseguramos que valdrá la pena el esfuerzo."

    [[params.faq]]
      question = "¿De quien es la propiedad intelectual de los proyectos?"
      answer = "De los creadores de los proyectos"

    [[params.faq]]
      question = "¿Cómo van a evaluar los proyectos?"
      answer = "Cada equipo tendrá 4 minutos para presentar su solución, los elementos que se van a evaluar son: <ul><li>Relevancia</li><li>Reproducibilidad</li><li>Impacto</li><li>Uso de datos del SESNA</li><ul>"

    [[params.faq]]
      question = "¿Qué tipo de entregables esperan?"
      answer = "ntendemos que por el tiempo de trabajo tan corto es difícil que puedas terminar un proyecto que la mayoría de los  entregables serán  de análisis descriptivo, sabemos que no hay tanta data para hacer  predicciones pero algunas ideas de que lo puedes entregar es:<br> Notebook de Jupyter<br>por su puesto Un Dashboard sería genial<br>Si trabajas con R un entregable con R y markdown eso puede funcionar "

  # Footer section
  [params.footer]
    enable = true
    copyright = ""

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/SESNAOficial"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/SESNAOficial"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-envelope-o"
      link = "mailto:dataton@sg.com.mx"
      title = "Correo electrónico"

    [[params.footer.quicklinks]]
      text = "Código de Conducta"
      link = "/info/coc"


