# Site settings
baseurl = "https://datatonanticorrupcion.mx/"
relativeURLs = true
languageCode = "es-mx"
defaultContentLanguage = "es"
title = "Datatón Anticorrupción"
theme = "dataton-agency"
publishDir = "docs"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-21077034-33"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/

  # Metadata for search engines
  name = "Dataton anticorrupcion"
  description = """El datatón anticorrupción es un evento donde construiremos herramientas 
  que utilicen datos abiertos con el fin de combatir la corrupción en México."""
  image = "https://datatonanticorrupcion.mx/img/dataton-card.png"
  twitter_user = "@SESNAOficial"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "No se encontró esa página"
    text = "Por favor visita [esta página](/)"

  # Navigation
  [params.navigation]
    brand = "Datatón Anticorrupción 2019"
    # Optional logo as brand stored in img/
    logo = "logo-navbar.svg"
    info = "Convocatoria"
    sede = "Sede"
 
    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. 

    # postpended links
    [[menu.postpend]]
      url = "/info/contexto"
      name = "Contexto"
      weight = 4

    [[menu.postpend]]
      url = "/info/datos"
      name = "Datos"
      weight = 6

    [[menu.postpend]]
      url = "/info/solicitud"
      name = "Participa"
      weight = 6

    [[menu.postpend]]
      url = "/info/preguntas-frecuentes"
      name = "Dudas"
      weight = 9

  # Sección de hero en homepage. 
  [params.hero]
  # Dado que el layout es muy particular para este evento, el contenido está 
  # hardcoded en layouts/partials/hero.html

  # Sección de información clave
  [params.info]
    enable = true
    title = "Convocatoria"
    description= """Te invitamos a participar en el datatón anticorrupción, un evento donde diseñaremos y construiremos 
herramientas digitales para detectar y combatir la corrupción por medio de datos abiertos, puedes consultar el <strong><a href="https://youtu.be/RFzfXy8XDN4">Webinar</a></strong> que realizamos con más información sobre los datos que vamos usar en el Datatón.

#### Fecha y sede
El evento se realizará el **sábado 7 de diciembre de 9 a 20 hrs** en la Escuela de Gobierno y Transformación Pública del Tecnológico de Monterrey, sede Mixcoac ubicada en 

> Av. Revolución 756, CDMX.

#### Tema
En esta edición nos enfocaremos en el tema de contrataciones públicas, y los resultados que generemos puedan implementarse en la Plataforma Digital Nacional a fin de contribuir en los esfuerzos para combatir la corrupción.

#### Dirigido a
Aunque la participación es abierta, consideramos que las personas que más pueden aportar son aquellas con experiencia 
en alguno de los siguientes campos: ciencia de datos, desarrollo de software, diseño UX, periodismo, comunicación, derecho, economía. Dado que tenemos 
una capacidad limitada en la sede, daremos prioridad de participación a las personas con estos roles.

#### Quién convoca
Este evento es una iniciativa de la [Plataforma Digital Nacional](https://plataformadigitalnacional.org) con el patrocinio de USAID, y es producido por <a href="https://sg.com.mx">Software Guru</a>.
"""

  # Sección para registro
  [params.registro]
  enable = true
  title = "¿Cómo participar?"
  description = "Si te interesa participar, por favor llena la [solicitud de participación](/info/solicitud)."

  # Sección para sede
  [params.sede]
  enable = false
  title = "Sede"
  name = "Escuela de Gobierno y Transformación Pública del Tecnológico de Monterrey"
  description = """Av. Revolución #756, Col. Mixcoac. CDMX
  https://escueladegobierno.itesm.mx/acerca-de-la-escuela
  """

  # Mentores
  [params.mentores]
    enable = true
    title = "Mentores"

    # Las fotos de los mentores se almacenan en 'static/img/team'.
    # Tratar de utilizar imágenes de por lo menos 360px*360px.

    [[params.mentores.members]]
      img = "andrew_leimdorfer.jpg"
      name = "Andrew Leimdorfer"
      position = "Sr Product Manager for Latin America at GDS"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/leimdorfer/"],
        ["fa-twitter", "https://twitter.com/Leimdorfer"]
      ]

    [[params.mentores.members]]
      img = "isela.jpg"
      name = "Isela Morquecho"
      position = "Directora de área en PDN"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/rosa-isela-morquecho-83535972/"],
      ]

      
    [[params.mentores.members]]
      img = "fernanda_mora.jpg"
      name = "Fernanda Mora"
      position = "Directora de área en PDN"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/fernanda-mora-alba-2588938a/"],
      ]

    [[params.mentores.members]]
      img = "benito_perdomo.jpg"
      name = "Benito Perdomo"
      position = "Director de Desarrollo de la PDN"
      social = [
        ["fa-github", "https://github.com/BenitoPerdomo"],
      ]

    [[params.mentores.members]]
      img = "sergio.jpg"
      name = "Sergio Rodríguez"
      position = "Subdirector de servicios informáticos de la PDN"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/sergio-rodr%C3%ADguez-segura-4458b579/"]
      ]

      [[params.mentores.members]]
      img = "nicolas.jpg"
      name = "José R. Nicolás Carlock"
      position = "Investigador del Observatorio de la Corrupción e Impunidad Instituto de Investigaciones Jurídicas, UNAM"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/jos%C3%A9-roberto-nicol%C3%A1s-carlock-a32927198/"],
        ["fa-twitter", "https://twitter.com/jrncarlock"]  
      ]

      [[params.mentores.members]]
      img = "jmcasanueva.jpg"
      name = "Juan Manuel Casanueva"
      position = "Fundador y Director @ Social TIC"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/jmcasanueva/"]
      ]

      [[params.mentores.members]]
      img = "andrea.jpg"
      name = "Andrea Deydén"
      position = "Editora de Política e Investigaciones Especiales @ El CEO"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/andrea-deyd%C3%A9n-1604b716/"],
        ["fa-twitter", "https://twitter.com/a_deyden"]
      ]

      [[params.mentores.members]]
      img = "toral.jpg"
      name = "Manuel Toral"
      position = "Secretario Técnico @ Consejo de la Judicatura Federal"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/josetoral/"]
      ]

      [[params.mentores.members]]
      img = "isaac.jpg"
      name = "Isaac Ortiz "
      position = "Secretario Técnico de la Auditoría Especial del Gasto Federalizado "
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/david-isaac-ortiz-calzada-850279199/"],
        ["fa-twitter", "https://twitter.com/Isaac_Ortiz26"]
      ]

      [[params.mentores.members]]
      img = "joseph.jpg"
      name = "Joseph Brandim-Howson"
      position = "Investigador en el Centro de Estudios Latinoamericanos, Universidad de Cambridge"
      social = [
        ["fa-link", "http://www.latin-american.cam.ac.uk/node/92/joseph-brandim-howson"]
      ]



  # Jueces
  [params.jueces]
    enable = true
    title = "Jueces"

    # Las fotos de los jueces se almacenan en 'static/img/team'.
    # Tratar de utilizar imágenes de por lo menos 360px*360px.

    [[params.jueces.members]]
      img = "chantal.jpg"
      name = "Chantal Donaldson-Foyer"
      position = "Head of Product at Government Digital Service, UK"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/chfoyer/"], 
        ["fa-twitter", "https://twitter.com/Ch_Foyer"]       
      ]

    [[params.jueces.members]]
      img = "romy_flores.jpg"
      name = "Romy Flores"
      position = "Directora de análisis para el proyecto Procura México en SHCP"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/romyflores/"],
        ["fa-twitter", "https://twitter.com/romyflores"] 
      ]

    [[params.jueces.members]]
      img = "pablo_villarreal.png"
      name = "Pablo Villarreal"
      position = "Titular de la Unidad de la Plataforma Digital Nacional"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/pablovillarreal/"],  
        ["fa-twitter", "https://twitter.com/pablo_vs1"]  
      ]

    [[params.jueces.members]]
      img = "sergio_alberto.jpg"
      name = "Sergio Alberto Martín Esquivel"
      position = "Consejero de la Organización Internacional de Integridad de la Administración Pública"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/sergio-alberto-martin-esquivel-62b48947"] 
      ]

    [[params.jueces.members]]
      img = "mario_torres.jpg"
      name = "Mario Alfonso Torres Rivera"
      position = "Director General Adjunto de la PDN"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/mario-torres"], 
        ["fa-github", "https://github.com/mariotorres"]       
      ]

    [[params.jueces.members]]
      img = "enrique.jpg"
      name = "Enrique Zapata"
      position = "Inteligencia de Datos y Nuevas Tecnologías en Banco de Desarrollo de América Latina (CAF)"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/enrique-zapata-14a12450/"],
        ["fa-twitter", "https://twitter.com/Enrique_Za"]  
      ]

      [[params.jueces.members]]
      img = "nicolas.jpg"
      name = "José R. Nicolás Carlock"
      position = "Investigador del Observatorio de la Corrupción e Impunidad Instituto de Investigaciones Jurídicas, UNAM"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/jos%C3%A9-roberto-nicol%C3%A1s-carlock-a32927198/"],
        ["fa-twitter", "https://twitter.com/jrncarlock"]  
      ]


#    [[params.jueces.members]]
#      img = "sofia_ramirez.jpg"
#      name = "Sofía Ramírez"
#      position = "Directora Adjunta de Investigación Aplicada @ Mexicanos contra la Corrupción y la Impunidad"
#      social = [
#        ["fa-twitter", "https://twitter.com/sofia_ramireza"],
#      ]

#    [[params.mentores.members]]
#      img = "alexandra_zapata.jpg"
#      name = "Alexandra Zapata"
#      position = "Directora de Educación e Innovación Cívica @ Instituto Mexicano para la Competitividad (IMCO)"
#      social = [
#        ["fa-twitter", "https://twitter.com/azapatah"],
#        ["fa-linkedin", "https://www.linkedin.com/in/azapatah/"]
#      ]
      
#    [[params.mentores.members]]
#      img = "jose_toral.jpg"
#      name = "José Manuel Toral"
#      position = "Especialista de datos @ Mexicanos contra la Corrupción y la Impunidad"
#      social = [
#        ["fa-twitter", "https://twitter.com/jmtoralc"],
#        ["fa-linkedin", "https://www.linkedin.com/in/josetoral/"]
#      ]

#    [[params.mentores.members]]
#      img = "jm_casanueva.jpg"
#      name = "Juan Manuel Casanueva"
#      position = "Director Ejecutivo @ Social TIC"
#      social = [
#        ["fa-twitter", "https://twitter.com/jm_casanueva"],
#        ["fa-linkedin", "https://www.linkedin.com/in/jmcasanueva/"]
#      ]

#    [[params.mentores.members]]
#      img = "jorge_a_castaneda.jpg"
#      name = "Jorge Andrés Castañeda"
#      position = "Coordinador de Proyectos @ Instituto Mexicano para la Competitividad (IMCO)"
#      social = [
#        ["fa-twitter", "https://twitter.com/jorgeacast"],
#        ["fa-linkedin", "https://www.linkedin.com/in/jorge-andres-castaneda-0044a75/"]
#      ]

#    [[params.mentores.members]]
#      img = "jesus_ramos.jpg"
#      name = "Jesús Ramos"
#      position = "Director de Operaciones @ Datank.ai"
#      social = [
#        ["fa-twitter", "https://twitter.com/xuxoramos"],
#        ["fa-linkedin", "https://www.linkedin.com/in/xuxoramos/"]
#      ]


  # Sponsors section
  # Los logos de los aliados están en 'static/img/logos'.
  # El tamaño ideal es 280px*80px
    [params.sponsors]
      enable = true
      center = true

    [params.sponsors1_list]
      enable = true
      title = "Patrocinado por"

      [[params.sponsors1]]
        logo = "usaid.png"
        link = "https://www.usaid.gov/es/mexico"



    [params.sponsors2_list]
      
      enable = true
      title = "Una iniciativa de " 

      [[params.sponsors2]]
        logo = "PDN_plataforma.png"
        link = "https://plataformadigitalnacional.org"

      [[params.sponsors2]]
        logo = "sesna.png"
        link = "https://www.gob.mx/sesna"

    [params.sponsors3_list]
      enable = true
      title = "Con el apoyo de" 

      [[params.sponsors3]]
        logo = "escuela-gobierno2.png"
        link = "https://escueladegobierno.itesm.mx"

      [[params.sponsors3]]
        logo = "shcp2.jpg"
        link = "https://www.gob.mx/hacienda"
      
      [[params.sponsors3]]
        logo = "msft.jpg"
        link = "https://developer.microsoft.com/es-es/"

      [[params.sponsors3]]
        logo = "cc.jpg"
        link = "https://cc.org.mx/"

      [[params.sponsors3]]
        logo = "asf.jpg"
        link = "https://www.asf.gob.mx/Default/Index"

      [[params.sponsors3]]
        logo = "uk2.png"
        link = "https://www.gov.uk/world/organisations/british-embassy-mexico-city.es-419"

      [[params.sponsors3]]
        logo = "caf2.png"
        link = "https://www.caf.com"

    [params.sponsors4_list]
      enable = true
      title = "Producido por"

      [[params.sponsors4]]
        logo = "sg.png"
        link = "https://sg.com.mx"

  #FAQ
  [params.faq_list]
    enable = true

    [[params.faq]]
      question = "¿Quiénes pueden participar?"
      answer = """La participación es abierta, pero tenemos cupo limitado. 
Consideramos que las personas que más pueden aportar son aquellas con experiencia en alguno de los 
siguientes campos: ciencia de datos, desarrollo de software, comunicación, economía, ciencias politicas, derecho y diseño. 

Si te interesa participar, por favor llena la forma de solicitud de participación. 
"""

    [[params.faq]]
      question = "¿Requiero llevar mi propio equipo de cómputo?"
      answer = "Sí, por favor lleva tu propio equipo."

    [[params.faq]]
      question = "Somos varias personas que queremos participar, ¿todos deben llenar la solicitud?"
      answer = "Sí, cada uno debe llenar la solicitud de participación."

    [[params.faq]]
      question = "¿Qué datos usaremos?"
      answer = "Puedes consultar los datos disponibles en la sección datos https://datatonanticorrupcion.mx/info/datos/"

    [[params.faq]]
      question = "¿Hay tamaño máximo de miembros por equipo?"
      answer = "5 personas es el máximo por equipo"

    [[params.faq]]
      question = "¿Hay premios?"
      answer = "Sí, El premio principal será un paquete con regalos y herramientas de utilidad para todos los perfiles en el equipo. No será dinero, pero te aseguramos que valdrá la pena el esfuerzo."

    [[params.faq]]
      question = "¿De quien es la propiedad intelectual de los proyectos?"
      answer = "De los creadores de los proyectos"

    [[params.faq]]
      question = "¿Qué tipo de entregables esperan?"
      answer = """
Las y los participantes tendrán que utilizar los estándares de los sistemas 2, 3 y 6 para generar entre ellos la relación de datos. Se espera que la relación de datos permita entender las conexiones que existen entre la información.
"""

    [[params.faq]]
      question = "¿Cómo van a evaluar los proyectos?"
      answer = "<p>Cada equipo tendrá un tiempo breve para presentar su propuesta. Se evaluarán los siguientes cinco elementos individualmente y al final se tendrá una calificación final sumando las calificaciones individuales:</p><ol><li>Uso de datos de la SESNA. Se calificará calculando el número de datasets usados.</li><li>Reproducibilidad. Vale 1 si los resultados se pueden reproducir en otra máquina y por otra persona. Vale 0 en otro caso.</li><li>Documentación. Vale 1 si existe un README (guía de implementación) de cómo correr el proyecto. Vale 0 en otro caso.</li><li>Uso de software libre. Vale 1 si todo el software que se usa es libre y gratuito, 0.5 si existe tanto software libre como propietario y 0 si es sólo uso de software propietario.</li><li>Impacto. Vale 1 si los resultados de la herramienta con respecto al objetivo del reto son de alto impacto, 0.5 si son de mediano impacto y 0 si son de bajo impacto.</li></ol>"
      
  # Footer section
  [params.footer]
    enable = true
    leyenda = "La realización del datatón anticorrupción es posible gracias al apoyo del pueblo de de los Estados Unidos a través de la Agencia de los Estados Unidos para el desarrollo Internacional (USAID). El evento es responsabilidad de los organizadores y no refleja necesariamente el punto de vista de USAID o del gobierno de los Estados Unidos de América."
    copyright = "Otro fantástico evento de <a href='https://sg.com.mx'>SG</a>."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/SESNAOficial"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/SESNAOficial"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-envelope-o"
      link = "mailto:dataton@sg.com.mx"
      title = "Correo electrónico"

    [[params.footer.quicklinks]]
      text = "Código de Conducta"
      link = "/info/coc"


